---

- name: java
  hosts: java

  roles:
    - java

- name: jdbc
  hosts: jdbc

  roles:
    - jdbc
    
- name: elasticsearch
  hosts: elasticsearch

  roles:
    - elasticsearch

- name: kibana
  hosts: kibana

  roles:
    - kibana

- name: logstash
  hosts: logstash

  roles:
    - logstash
