---

- name: Java
  hosts: java

  roles:
    - java

- name: elasticsearch
  hosts: elasticsearch

  roles:
    - elasticsearch

- name: kibana
  hosts: kibana

  roles:
    - kibana

- name: logstash
  hosts: logstash

  roles:
    - logstash
