---

- name: restart kibana
  service: 
    name: kibana
    enabled: yes
    state: restarted
  listen: "restart kibana"

- name: restart rsyslog
  service: 
    name: rsyslog
    state: restarted
  listen: "restart logging"

